### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by digitaltvguy** [ifb/vapoursynth-colorbars#2]
Can you supply recommended Linux for compiling.  I'm having issues with the VapourSynth dependencies:

./configure: line 12953: syntax error near unexpected token `VapourSynth,'
./configure: line 12953: `PKG_CHECK_MODULES(VapourSynth, vapoursynth)'

**Comment by digitaltvguy** [comment]
I would also like to build in OSX.  ...any chance someone made a brew formula?

**Comment by digitaltvguy** [comment]
OK, I compiled successfully but need more detail on it's usage with VapourSynth.  Do you have some thorough examples?  ...very much appreciated :)

**Comment by ifb** [comment]
There are four examples in the README, but I glanced at your repo and it looks like you have it figured out now.

I don't have OSX to test with, nor any interest in it but patches are welcome if there is an actual problem compiling (not some build environment/pkg-config nonsense).
