### ISSUE TITLE
Can you provide a full example of usage (a script and procedure to load module)

### ISSUE THREAD

**Issue by digitaltvguy** [ifb/vapoursynth-colorbars#3]
This is a fantastic idea and would love to experiment with it.  I'm a newbie with VapourSynth, but comfortable in command line.  I've got VapourSynth and VapourSynth-colorbars compiled and ready to go.

Your help is appreciated!

-Chris

**Comment by digitaltvguy** [comment]
I came up with this (put contents in HLG_2020_1080_p59.94.vpy)(for some reason it didn't export v210 but instead planar 422):


***************************************************
from vapoursynth import core

import vapoursynth as vs

c = core.colorbars.ColorBars(format=vs.RGB30, resolution=5, hdr=1)
c = core.std.Convolution(c,mode="h",matrix=[1,2,4,2,1])
c = core.resize.Point(clip=c,format=vs.YUV422P10,matrix_s="2020ncl")
c = c * (1 * 60000 // 1001)
c = core.std.AssumeFPS(clip=c, fpsnum=60000, fpsden=1001)

enable_v210 = True

c.set_output()

**Comment by ifb** [comment]
I think you need to move 
`enable_v210 = True`
to the top of the script to work.
