### ISSUE TITLE
When i run Colorbars, it crashes

### ISSUE THREAD

**Issue by rgm89git** [ifb/vapoursynth-colorbars#9]
I'm using Vapoursynth R61 and Colorbars R3, but for some strange reason, when i run the script, it just crashes.

Even without ANY argument, it still crashes.

Can you help me? Or fix this issue?

**Comment by ifb** [comment]
I'm pretty sure R3 works with Vapoursynth R61, but there were some API changes that broke things.  I need to release an R4 anyway.  Can you compile the lastest master and test?

**Comment by rgm89git** [comment]
Oh, it did work. Thanks a lot.
